### ISSUE TITLE
Devicon customization

### ISSUE THREAD

**Issue by Runebranch** [nrandecker/particle#3]
I'm having trouble finding where the Devicon/Icon headers are located or referenced to customize them. Can you help?

**Comment by nrandecker** [comment]
Yes, the Devicons can be found at [devicon](http://devicon.fr/).

If you would like to modify which icons are used update the about.html file.

```
<i class="devicon-javascript-plain colored"></i>
      <i class="devicon-react-original-wordmark colored"></i>
      <i class="devicon-nodejs-plain-wordmark"></i>
```
Change these to whatever icon you want by updating the class ex. 
```
<i class="devicon-angularjs-plain colored"></i>
```

The icons are loaded by a cdn link so you can just update the classes to whatever icon you want.

**Comment by Runebranch** [comment]
Thank you
