### ISSUE TITLE
background_image for Particles

### ISSUE THREAD

**Issue by tannguyen16** [nrandecker/particle#37]
Hi,
I want to set a different background_image for the header particles instead of the given color. But trying to change the field "background" or adding a field "background-image: url('/assets/img/background.jpg')" in  /src/styles/_header.scss does not work for me. Did I do something wrong?
Thank you!

**Comment by a-fakhri** [comment]
@nrandecker I ran into the same issue. Is this because adjusting properties scss files won't take effect unless we compile everything with Jerkyll?

**Comment by a-fakhri** [comment]
@tannguyen16 if you're still curious, it is not enough to just change the field. You need to recompile the assets with Jerkyll. You can test out the changes locally, following directions listed in the gh-pages branch.

@nrandecker, thanks for the template, awesome design!
