### ISSUE TITLE
Can't initialize locally

### ISSUE THREAD

**Issue by BeCuriousS** [nrandecker/particle#57]
Hi there. When searching for a nice looking page template for github pages I found this particle theme. I like it very much. I wanted to set it up locally to play around with the webpage before publishing it. Since now I was not able to set it up. I am experienced with python and docker but not with web development. I tryed to run this in an ubuntu docker container on a windows machine but failed because of errors when running the suggested steps for local setup from the readme (installing nodejs, etc.).
Could you provide a more detailed description on the steps for a local setup (versions of nodejs etc.)? Maybe you have some suggestions to run this in docker?

My error log:
[log.txt](https://github.com/nrandecker/particle/files/5311328/log.txt)

**Comment by matteobruni** [comment]
Same error here, I made a PR using tsParticles instead of particles.js without compiling it. Since the latest commit is some years old I think the packages need some updates

**Comment by rudiruhl** [comment]
I think you have to update the dependencies in your `package.json`.
