### ISSUE TITLE
update instructions to customize particles

### ISSUE THREAD

**Issue by aliciapaz** [nrandecker/particle#63]
When trying to customize the code for the particles canvas, I noticed that the changes must go in `assets/js/main.js` instead of `app.js`.
btw, very nice theme! thank you.

**Comment by mehdichaouch** [comment]
`assets/js/main.js` is a generated file [made by Gulp](https://github.com/nrandecker/particle/blob/master/gulpfile.js#L73) based on JavaScript files in `src/js`. You should not modify `main.js`.
Check [running-the-blog-in-local](https://github.com/nrandecker/particle#running-the-blog-in-local) to see how stuff are made.
